- name: Change default account password
  vmware_vm_shell:
    hostname: "{{ vmware_guest_hostname }}"
    username: "{{ vmware_guest_username }}"
    password: "{{ vmware_guest_password }}"
    validate_certs: "{{ vmware_guest_validate_certs }}"
    # ---
    vm_id: "{{ vmware_guest_name }}"
    folder: "{{ vmware_guest_folder }}"
    # ---
    vm_username: "{{ vmware_guest_vm_username }}"
    vm_password: "{{ vmware_guest_vm_password }}"
    vm_shell: "{{ vmware_guest_vm_shell }}"
    vm_shell_args: "-c 'echo {{ vmware_guest_vm_username }}:{{ vmware_guest_init_password }} | chpasswd'"
    vm_shell_cwd: "/"
  delegate_to: "{{ vmware_guest_delegated_host }}"
  when:
    - vmware_guest_init_password | default('') | length > 0
  delay: 10
  tags: [never, init]
