# code: language=Ansible insertSpaces=true tabSize=2


- name: Initialize sudo (cleanup pre-init conf)
  vmware_vm_shell:
    hostname: "{{ vmware_guest_hostname }}"
    username: "{{ vmware_guest_username }}"
    password: "{{ vmware_guest_password }}"
    validate_certs: "{{ vmware_guest_validate_certs }}"
    # ---
    vm_id: "{{ vmware_guest_name }}"
    folder: "{{ vmware_guest_folder }}"
    # ---
    vm_username: "{{ _vmware_guest_vm_username }}"
    vm_password: "{{ _vmware_guest_vm_password }}"
    vm_shell: "{{ vmware_guest_vm_shell }}"
    vm_shell_args: "-c 'sudo rm {{ vmware_guest_init_sudo_path }}'"
    vm_shell_cwd: "/"
  delegate_to: "{{ vmware_guest_delegated_host }}"
  register: _init_sudo
  until: not _init_sudo.failed
  retries: 2
  delay: 10
  tags: [never, init]
